version: 0.2

phases:
  install:
    runtime-versions:
      python: $LAMBDA_PY_RUNTIME

  build:
    commands:
      - echo ">>> Avvio ciclo per creazione layers"
      - |
        LAYER_ARNS=()
        for LIB in $LIBS_LAYER; do
          echo ">>> Creazione layer per libreria: $LIB"
          mkdir -p python
          pip3 install "$LIB" -t python/
          rm -rf python/__pycache__ python/tests python/*.dist-info/test*
          ZIP_NAME="${LIB}_layer.zip"
          zip -r "$ZIP_NAME" python
          echo ">>> Upload su S3";
          aws s3 cp "$ZIP_NAME" s3://$S3_BUCKET/$LAYER_S3_PATH/$ZIP_NAME;
          LAYER_ARN=$(aws lambda publish-layer-version \
            --layer-name "${LIB}_layer" \
            --zip-file fileb://"$ZIP_NAME" \
            --compatible-runtimes "python$LAMBDA_PY_RUNTIME" \
            --region "$AWS_REGION" \
            --query 'LayerVersionArn' --output text)
          echo ">>> ARN creato: $LAYER_ARN"
          LAYER_ARNS+=($LAYER_ARN)
          rm -rf python "$ZIP_NAME"
        done
        echo ">>> Layers creati: ${LAYER_ARNS[@]}"
        aws lambda update-function-configuration \
          --function-name "$LAMBDA_ARN" \
          --layers ${LAYER_ARNS[@]}

artifacts:
  files: []